default: &default
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    raise_not_found_error: false

development:
  <<: *default

test:
  <<: *default

staging:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        ssl_ca_cert: rds-combined-ca-bundle.pem

production:
  <<: *default
