source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'
gem 'graphql'
gem 'mongoid', '~>7.1.0'
# soft-deleted
gem "mongoid-falsehoods"
gem 'jwt'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'dotenv-rails'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
gem 'sidekiq', '~> 5.2.8'
gem 'redis'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Http REST CLIENT
gem 'faraday'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails', '~> 4.0.0'
  gem "factory_bot_rails"
  gem 'ffaker'
  gem 'pry'
  gem 'pry-rails'
  gem 'database_cleaner-mongoid'
  gem 'rubocop', require: false
  gem "vcr"
  gem "webmock"
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "letter_opener_web"
end

group :development, :staging do
  gem 'graphiql-rails'
end

gem "bugsnag", "~> 6.19"
